"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
type Doc={id:string;title:string;text:string;version:number;createdAt:string;updatedAt:string};
const shell={minHeight:'100vh',background:'radial-gradient(circle at 20% 10%,rgba(76,126,255,.14),transparent 28%),#05070b',color:'#f7f9fc',padding:'24px',fontFamily:'Inter,system-ui,sans-serif'} as const;
export default function DocsPage(){const [docs,setDocs]=useState<Doc[]>([]);const [active,setActive]=useState<Doc|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/docs',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar');setDocs(d.documents??[]);setActive((cur)=>cur??d.documents?.[0]??null);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar');}finally{setLoading(false);}}
useEffect(()=>{void load();},[]);
async function createDoc(){setError('');const r=await fetch('/api/docs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Novo documento'})});const d=await r.json();if(!r.ok||!d.document){setError(d.error||'Não foi possível criar');return;}setDocs((x)=>[d.document,...x]);setActive(d.document);setSuccess('Documento criado.');}
async function save(){if(!active||saving)return;setSaving(true);setError('');setSuccess('');try{const r=await fetch('/api/docs',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:active.id,title:active.title,text:active.text,version:active.version})});const d=await r.json();if(!r.ok||!d.document)throw new Error(d.error||'Não foi possível salvar');setActive(d.document);setDocs((x)=>x.map((item)=>item.id===d.document.id?d.document:item));setSuccess(`Salvo · versão ${d.document.version}`);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar');}finally{setSaving(false);}}
async function remove(){if(!active||!window.confirm(`Excluir “${active.title}”?`))return;const r=await fetch('/api/docs',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:active.id})});const d=await r.json();if(!r.ok){setError(d.error||'Não foi possível excluir');return;}const next=docs.filter((x)=>x.id!==active.id);setDocs(next);setActive(next[0]??null);setSuccess('Documento excluído.');}
return <main style={shell}><header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',marginBottom:28}}><Link href="/dashboard" style={{color:'#fff',fontWeight:900,letterSpacing:2,textDecoration:'none'}}>NEYVIX DOCS</Link><div style={{display:'flex',gap:10}}><button onClick={()=>void createDoc()} style={btn}>+ Novo documento</button><Link href="/dashboard" style={{...btn,textDecoration:'none'}}>Central de Comando</Link></div></header><section style={{display:'grid',gridTemplateColumns:'minmax(220px,320px) 1fr',gap:20,maxWidth:1400,margin:'0 auto'}}><aside style={card}><p style={eyebrow}>BIBLIOTECA PRIVADA</p><h1 style={{fontSize:24,margin:'6px 0 18px'}}>Seus documentos</h1>{loading?<p role="status">Carregando…</p>:docs.length?docs.map((doc)=><button key={doc.id} onClick={()=>{setActive(doc);setError('');setSuccess('');}} style={{...row,outline:active?.id===doc.id?'1px solid rgba(126,166,255,.7)':'none'}}><strong>{doc.title}</strong><small>v{doc.version} · {new Date(doc.updatedAt).toLocaleString('pt-BR')}</small></button>):<p style={{opacity:.62}}>Nenhum documento ainda. Crie o primeiro para começar.</p>}</aside><section style={{...card,minHeight:'70vh'}}>{active?<><div style={{display:'flex',gap:12,alignItems:'center',marginBottom:14}}><input aria-label="Título do documento" value={active.title} maxLength={160} onChange={(e)=>setActive({...active,title:e.target.value})} style={titleInput}/><button onClick={()=>void save()} disabled={saving||!active.title.trim()} style={btn}>{saving?'Salvando…':'Salvar'}</button><button onClick={()=>void remove()} style={dangerBtn}>Excluir</button></div><textarea aria-label="Conteúdo do documento" value={active.text} maxLength={200000} onChange={(e)=>setActive({...active,text:e.target.value})} placeholder="Comece a escrever…" style={editor}/><div style={{display:'flex',justifyContent:'space-between',gap:12,marginTop:12,opacity:.72,fontSize:13}}><span>{active.text.length.toLocaleString('pt-BR')} caracteres</span><span>Versão {active.version}</span></div></>:<div style={{display:'grid',placeItems:'center',minHeight:'55vh',textAlign:'center',opacity:.72}}><div><h2>Um espaço limpo para pensar e construir.</h2><p>Crie um documento. O conteúdo fica vinculado somente à sua conta.</p></div></div>}{error?<p role="alert" aria-live="assertive" style={{color:'#ff9ca8'}}>{error}</p>:null}{success?<p role="status" aria-live="polite" style={{color:'#9de7c1'}}>{success}</p>:null}</section></section></main>}
const card={background:'linear-gradient(180deg,rgba(17,23,34,.92),rgba(8,12,19,.94))',border:'1px solid rgba(255,255,255,.08)',borderRadius:24,padding:20,boxShadow:'0 24px 80px rgba(0,0,0,.35)'} as const;const btn={background:'rgba(255,255,255,.08)',color:'#fff',border:'1px solid rgba(255,255,255,.1)',borderRadius:12,padding:'10px 14px',cursor:'pointer'} as const;const dangerBtn={...btn,color:'#ffb4bc'} as const;const row={width:'100%',textAlign:'left',display:'grid',gap:6,background:'rgba(255,255,255,.035)',color:'#fff',border:'0',borderRadius:14,padding:14,marginBottom:8,cursor:'pointer'} as const;const titleInput={flex:1,minWidth:0,background:'transparent',color:'#fff',border:'0',borderBottom:'1px solid rgba(255,255,255,.12)',fontSize:26,fontWeight:800,padding:'10px 4px',outline:'none'} as const;const editor={width:'100%',minHeight:'56vh',resize:'vertical',background:'rgba(0,0,0,.18)',color:'#edf2fb',border:'1px solid rgba(255,255,255,.08)',borderRadius:18,padding:20,font:'16px/1.75 Inter,system-ui,sans-serif',outline:'none'} as const;const eyebrow={fontSize:11,letterSpacing:2.2,opacity:.58,fontWeight:800} as const;
