import { neon } from "@neondatabase/serverless";

export type NeyvixDocument = { id:string; title:string; text:string; version:number; createdAt:string; updatedAt:string };
function getSql(){ const url=process.env.DATABASE_URL?.trim(); return url?neon(url):null; }
async function ready(sql: NonNullable<ReturnType<typeof getSql>>){ const r=await sql`SELECT to_regclass('public.documents')::text AS documents`; return Boolean((r as Array<{documents:string|null}>)[0]?.documents); }
function map(row:Record<string,unknown>):NeyvixDocument{ const content=(row.content??{}) as Record<string,unknown>; return { id:String(row.id), title:String(row.title), text:typeof content.text==='string'?content.text:'', version:Number(row.version??1), createdAt:String(row.created_at), updatedAt:String(row.updated_at) }; }
export async function listDocuments(email:string){ const sql=getSql(); if(!sql||!(await ready(sql))) return []; const rows=await sql`SELECT d.id,d.title,d.content,d.version,d.created_at,d.updated_at FROM public.documents d JOIN public.users u ON u.id=d.owner_user_id WHERE lower(u.email)=${email.trim().toLowerCase()} AND u.is_active=true ORDER BY d.updated_at DESC LIMIT 100`; return (rows as Array<Record<string,unknown>>).map(map); }
export async function createDocument(email:string,title:string){ const sql=getSql(); if(!sql||!(await ready(sql))) return null; const clean=title.trim().slice(0,160)||'Sem título'; const rows=await sql`INSERT INTO public.documents(owner_user_id,title,content) SELECT id,${clean},jsonb_build_object('text','') FROM public.users WHERE lower(email)=${email.trim().toLowerCase()} AND is_active=true RETURNING id,title,content,version,created_at,updated_at`; return rows[0]?map(rows[0] as Record<string,unknown>):null; }
export async function updateDocument(email:string,id:string,title:string,text:string,expectedVersion:number){ const sql=getSql(); if(!sql||!(await ready(sql))) return null; const rows=await sql`UPDATE public.documents d SET title=${title.trim().slice(0,160)||'Sem título'},content=jsonb_build_object('text',${text}::text),version=d.version+1,updated_at=now() FROM public.users u WHERE d.id=${id}::uuid AND d.version=${expectedVersion} AND u.id=d.owner_user_id AND lower(u.email)=${email.trim().toLowerCase()} AND u.is_active=true RETURNING d.id,d.title,d.content,d.version,d.created_at,d.updated_at`; return rows[0]?map(rows[0] as Record<string,unknown>):null; }
export async function deleteDocument(email:string,id:string){ const sql=getSql(); if(!sql||!(await ready(sql))) return false; const rows=await sql`DELETE FROM public.documents d USING public.users u WHERE d.id=${id}::uuid AND u.id=d.owner_user_id AND lower(u.email)=${email.trim().toLowerCase()} AND u.is_active=true RETURNING d.id`; return rows.length===1; }
